
\version "2.24.0"
\relative c' {
  \clef bass
  \key c \major
  e'4-\markup { \finger 1 }
  d4-\markup { \finger 0 }
  c,4-\markup { \finger 0 }
  f'4-\markup { \finger 2 }
  c,4-\markup { \finger 0 }
  e'4-\markup { \finger 1 }
  c4-\markup { \finger 4 }
  c4-\markup { \finger 4 }
  e,4-\markup { \finger 3 }
  d'4-\markup { \finger 0 }
  b4-\markup { \finger 3 }
  b4-\markup { \finger 3 }
  b'4-\markup { \finger 1 }
  c,,4-\markup { \finger 0 }
  d''4-\markup { \finger 4 }
  e,,4-\markup { \finger 3 }
  b''4-\markup { \finger 1 }
  c,,4-\markup { \finger 0 }
  d'4-\markup { \finger 0 }
  f4-\markup { \finger 2 }
  b4-\markup { \finger 3 }
  d'4-\markup { \finger 4 }
  a,4-\markup { \finger 1 }
  c,4-\markup { \finger 0 }
  d'4-\markup { \finger 0 }
  e,4-\markup { \finger 3 }
  g'4-\markup { \finger 4 }
  d,4-\markup { \finger 1 }
  g4-\markup { \finger 0 }
  c'4-\markup { \finger 4 }
  e,4-\markup { \finger 3 }
  c4-\markup { \finger 0 }
  f'4-\markup { \finger 2 }
  g,4-\markup { \finger 0 }
  e4-\markup { \finger 3 }
  c''4-\markup { \finger 2 }
  d4-\markup { \finger 4 }
  b4-\markup { \finger 1 }
  e,,4-\markup { \finger 3 }
  f'4-\markup { \finger 2 }
  g4-\markup { \finger 4 }
  e4-\markup { \finger 1 }
  b4-\markup { \finger 3 }
  c4-\markup { \finger 4 }
  f4-\markup { \finger 2 }
  a'4-\markup { \finger 0 }
  d4-\markup { \finger 4 }
  d,4-\markup { \finger 0 }
  d4-\markup { \finger 0 }
  c4-\markup { \finger 4 }
  d'4-\markup { \finger 4 }
  g,4-\markup { \finger 4 }
  a4-\markup { \finger 1 }
  d'4-\markup { \finger 4 }
  d,,4-\markup { \finger 1 }
  d''4-\markup { \finger 4 }
  c,4-\markup { \finger 4 }
  b'4-\markup { \finger 1 }
  c4-\markup { \finger 2 }
  d,,4-\markup { \finger 1 }
  e'4-\markup { \finger 1 }
  a4-\markup { \finger 1 }
  f4-\markup { \finger 2 }
  g4-\markup { \finger 4 }
  f,4-\markup { \finger 4 }
  d'4-\markup { \finger 0 }
  a'4-\markup { \finger 0 }
  f,4-\markup { \finger 2 }
  d4-\markup { \finger 0 }
  e4-\markup { \finger 1 }
  e4-\markup { \finger 1 }
  e,4-\markup { \finger 3 }
  e'4-\markup { \finger 1 }
  c'4-\markup { \finger 2 }
  c4-\markup { \finger 2 }
  b4-\markup { \finger 1 }
  d,4-\markup { \finger 0 }
  g,4-\markup { \finger 0 }
  e4-\markup { \finger 3 }
  e'4-\markup { \finger 1 }
}
